### ISSUE TITLE
Ошибка при выполнении кода "Мерка 1.6"

### ISSUE THREAD

**Issue by Metanschik** [buchlotnik/Merka#1]
Ошибка при выполнении кода "Мерка 1.6"
![Снимок](https://user-images.githubusercontent.com/101040266/156916100-ba6f3bfd-8f60-4e23-bdb1-1911ba841735.JPG)

Что бы это значило
![Снимок 1](https://user-images.githubusercontent.com/101040266/156916123-9159bd33-1e95-479b-8e45-dc9b1f9b923d.JPG)

**Comment by buchlotnik** [comment]
хотелось бы чуть больше подробностей - при каких обстоятельствах, разово или постоянно, какая версия офиса - потому как первый раз за два года эксплуатации сообщение об ошибке

**Comment by Metanschik** [comment]
Добрый вечер!

 

Версии офиса две – 2013 и 2019

 

Ошибка постоянно, запустить тест скорости не получилось не разу, постоянно ошибка.

 

Для теста направляю файл на котором тестирую

 

Может модель данных у меня кривая, или связи не такие как надо.

 

 

С уважением

Слободчиков Игорь Михайлович

**Comment by Metanschik** [comment]
[Производственная программа 2023 тест.zip](https://github.com/buchlotnik/Merka/files/8199319/2023.zip)

Файл в котором не работает

**Comment by buchlotnik** [comment]
Здравствуйте.

Спасибо за интересный пример. В нём действительно есть подключение с названием **Подключение** и оно пустое (Connection.Type = xlConnectionTypeNOSOURCE). На нём всё и падало (отрадно, что не только в моей надстройке). Прошу протестировать только что загруженную версию **1.6.1**
